---
- name: Converge
  hosts: all
  roles:
    - role: onaio.postgresql
      vars:
        postgresql_version: 10
        postgresql_users:
          - name: rapidpro
            pass: rapidpro
            encrypted: true
        postgresql_databases:
          - name: rapidpro
            owner: rapidpro
            encoding: "UTF-8"
            hstore: true
            gis: true
        postgresql_database_extensions:
          - db: rapidpro
            extensions:
              - postgis
        postgresql_ext_install_postgis: true
        postgresql_ext_postgis_version: "2.5"
        postgresql_ext_postgis_deps:
          - libgeos-c1v5
          - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
          - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}-scripts"
        postgresql_fdw_mysql_packages: "postgresql-{{ postgresql_version }}-mysql-fdw"
        postgresql_fdw_ogr_packages: "postgresql-{{ postgresql_version }}-ogr-fdw"
        postgresql_backup_enabled: false

    - role: DavidWittman.redis
      vars:
        redis_version: "2.8.9"

    - role: ansible-rapidpro
      vars:
        rapidpro_postgresql_password: rapidpro
        rapidpro_gdal_version: "1.11.2"
        rapidpro_system_wide_dependencies:
          - build-essential
          - git
          - python3.6-dev
          - python3-distutils-extra
          - libgdal-dev
          - python3-gdal
          - gdal-bin
          - libxml2-dev
          - libxslt1-dev
          - lib32ncurses5-dev
          - tcl8.5
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python-psycopg2
          - nodejs
          - npm
          - node-less
          - coffeescript
          - libffi6
          - libffi-dev
