---
- name: Converge
  hosts: all
  roles:
    - role: ANXS.postgresql
      vars:
        postgresql_version: 10
        postgresql_users:
          - name: rapidpro
            pass: rapidpro
            encrypted: true
        postgresql_databases:
          - name: rapidpro
            owner: rapidpro
            encoding: "UTF-8"
            hstore: true
            gis: true
        postgresql_database_extensions:
          - db: rapidpro
            extensions:
              - postgis
        postgresql_ext_install_postgis: true
        postgresql_ext_postgis_version: "2.5"

    - role: DavidWittman.redis
      vars:
        redis_version: "2.8.9"

    - role: ansible-rapidpro
      vars:
        rapidpro_postgresql_password: rapidpro
        rapidpro_apt_python_ppa: "ppa:deadsnakes/ppa"
        rapidpro_python_source_version: "3.7"
        rapidpro_gdal_version: "1.11.2"
        rapidpro_system_wide_dependencies:
          - build-essential
          - git
          - python3.7-dev
          - python3.7-distutils
          - libgdal-dev
          - python3-gdal
          - gdal-bin
          - libxml2-dev
          - libxslt1-dev
          - lib32ncurses5-dev
          - tcl8.5
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python-psycopg2
          - nodejs
          - nodejs-legacy
          - npm
          - node-less
          - coffeescript
          - libffi6
          - libffi-dev
